Accueil static
WildCodeSchool/tlse0320-p2-ContainmentCooker pull request #2
Opened 2020-04-17 15:00 UTC by llopezjosue

- Pull request de la branche accueil static qui contient la mise à jour du site web à l'étape de la présentation de projet de la semaine 2.
-  Correspond à la userstory de réalisation de la page d'accueil simple et esthétique qui comporte :
 un header, une banner, une research bar, une liste des catégories  et un footer

2020-04-17 15:07 UTC, TOBOTOMAS31 submitted a review, later dismissed
Le code est bon, aucun changements à prévoir pour le moment.

2020-04-17 15:11 UTC, AdrienFaure31 submitted a review, later dismissed
Le code est nickel !!

2020-04-17 15:12 UTC, TOBOTOMAS31 submitted a review, later dismissed
code ok, les changements fait sont ok

2020-04-20 10:11 UTC, Froyj requested changes
Resoumettre avec package-lock.json en moins ==> 15 000 ligne (0_0') 
En tant que formateur, je souhaiterai pouvoir savoir la taille exacte de la PR afin de savoir si c'est pertinent de m'engager dans cette activité fastidieuse :p

2020-04-22 08:23 UTC, TOBOTOMAS31 approved these changes
le package-lock.json a bien était supprimer afin d'alléger le code

2020-04-22 14:13 UTC, Froyj approved these changes
Je valide mais attention à contrôler la taille de vos fichier css. N'hesitez pas repérer les règles CSS qui sont appliquées de manière globale, celle qui ne sont appelées que dans certains composants afin de garder des fichiers css faciles à manipuler (idéalement - de 100 lignes). Il y a pléthore d'articles sur le sujet sur le net.
Attention également 40 fichiers ==> quasiment 997 lignes de modif (c'est trop). A partir de maintenant on privilégie les petites PR (1 issue = 1 PR).

2020-04-22 14:31 UTC, merged