Test recipe click
WildCodeSchool/tlse0320-p2-ContainmentCooker pull request #21
Opened 2020-05-12 07:34 UTC by llopezjosue

Lorsque je clique sur une recette affichée dans une catégorie ou suite à une recherche, une page composée des détails de la recette apparaît.
Composant fonctionnel, il ne reste qu'à réorganiser la page avec du Css.

2020-05-12 07:36 UTC, TOBOTOMAS31 submitted a review, later dismissed
Fonctionnalité ok ! Mise en place avec travail de groupe !

2020-05-12 07:38 UTC, thierry-a submitted a review, later dismissed
Code fonctionne ok!

2020-05-12 09:07 UTC, Froyj requested changes

2020-05-12 09:07 UTC, Froyj commented on src/components/RecipeClick.jsx
> +/* eslint-disable react/destructuring-assignment */
:scream: 

allez on assume les règles eslint

2020-05-13 15:13 UTC, Froyj approved these changes

2020-05-13 15:41 UTC, closed without merging