Random recipe
WildCodeSchool/tlse0320-p2-ContainmentCooker pull request #5
Opened 2020-04-22 14:33 UTC by llopezjosue

Conformément à la demande du client, fonctionnalité d'affichage d'une recette aléatoire.
    Création de la page d'affichage de recette
    Titre et button de la bannière de la page d'accueil qui renvoit à une page de recette qui affiche aléatoirement une recette depuis l'api

2020-04-22 14:35 UTC, llopezjosue commented on src/App.jsx
> +      <BrowserRouter>
Ajout de react router pour naviguer entre la page homme et recette

2020-04-22 14:39 UTC, llopezjosue reviewed
j'ai rajouté des commentaire pour suivre le déroulement de la pr

2020-04-22 14:39 UTC, llopezjosue commented on src/components/Banner.jsx
> +          <Link to="/randompage" className="TitleRecipe">
Ajout de react router pour naviguer entre la page home et recette

2020-04-22 14:39 UTC, llopezjosue commented on src/components/Css/RecipeCard.css
> +.CardRecipe {
css du nouveau composant recipecard

2020-04-22 14:39 UTC, llopezjosue commented on src/components/RecipeCard.jsx
> +/* eslint-disable react/prop-types */
creation de recipe card

2020-04-23 06:23 UTC, TOBOTOMAS31 submitted a review, later dismissed
Ok. L'utilisateur a bien accès à une recette depuis la bannière, ensuite il peu charger une nouvelle recette aléatoire depuis une nouvelle page.

2020-04-23 09:07 UTC, Froyj requested changes
Bien ! C'est le format que j'attends pour une PR :slightly_smiling_face:

2020-04-23 09:07 UTC, Froyj commented on src/components/RecipeCard.jsx
> +/* eslint-disable react/prop-types */
On enlève et on va se renseigner pour voir ce que sont les proptypes (rien de très compliqué)

2020-04-23 12:05 UTC, llopezjosue commented on src/components/RecipeCard.jsx
> +/* eslint-disable react/prop-types */
Yes je me souviens de quoi il recourt, je fais ça après le talk !

2020-04-24 06:09 UTC, TOBOTOMAS31 approved these changes
propType bien ajoutée

2020-04-24 08:17 UTC, Froyj approved these changes

2020-04-24 08:21 UTC, merged