Recipeslist by category
WildCodeSchool/tlse0320-p2-ContainmentCooker pull request #7
Opened 2020-04-23 07:01 UTC by TOBOTOMAS31

Fonctionnalité : en tant qu'utilisateur je veux pourvoir accéder à la liste des recettes d'une categorie lorsque j'en sélectionnerai une depuis la page d'accueil dans la section "categories".
Attention il faut penser à installer FontAwesome 'npm install fontawesome' pour avoir l'icône 'coeur' (fonctionnalité à mettre en place dans autre PR).
J'ai créé la page 'ListPage.jsx' faisant apparaître la liste des recettes sous forme de carte,  on y accède depuis la page Home après avoir cliquer sur une catégorie.

2020-04-23 08:38 UTC, llopezjosue submitted a review, later dismissed
Composant ok, code fonctionnel. Peut être la prochaine fois diviser la pr en 2 avec d'un côté le css corrigé et de l'autre la fonctionnalité

2020-04-23 09:30 UTC, Froyj requested changes
La PR est bien construite 
A revoir cette histoire d'affichage de la liste des catégories et c'est nickel

2020-04-23 09:30 UTC, Froyj commented on src/components/Categories.jsx
> +        <Col className="container-image">
Ici, tu affiches manuellement la liste des recette or il me semble que l'on a un point de l'API qui nous permet de récupérer la liste des catégories. Récupère plutot cette liste, créé toi un composant CardCatgory et map sur la liste de catégories pour avoir un rendu dynamique basé sur la liste fetched depuis l'API.

2020-04-23 09:30 UTC, Froyj commented on src/components/RecipesList.jsx
> +import React from 'react';
Regler le code en rouge dans ESLint

2020-04-23 11:37 UTC, TOBOTOMAS31 commented on src/components/RecipesList.jsx
> +import React from 'react';
je ne comprend pas

2020-04-23 11:44 UTC, TOBOTOMAS31 commented on src/components/Categories.jsx
> +        <Col className="container-image">
En effet on a la possiblité de faire un appel API pour avoir la liste des catégories mais on a seulement le nom des catégories, elle ne fournit pas une image avec la catégorie. Donc j'aurais des card sans image.

2020-04-23 11:45 UTC, TOBOTOMAS31 commented on src/components/RecipesList.jsx
> +import React from 'react';
j'ai pas compris ta demande

2020-04-23 18:48 UTC, llopezjosue submitted a review, later dismissed
propTypes rajoutés, c'est ok

2020-04-24 08:18 UTC, Froyj submitted a review, later dismissed

2020-04-24 08:40 UTC, llopezjosue approved these changes
Conflits résolus

2020-04-24 08:47 UTC, Alexandra31150 approved these changes
Review ok

2020-04-24 08:48 UTC, merged